spring:
  application:
    name: discovery-service

# Server configuration
server:
  port: 8761

# Eureka client configuration
eureka:
  client:
    fetch-registry: false      # Disable the Config Server
    register-with-eureka: false # Disable service discovery